"""UI109 printed document-definition and Help acceptance in fictional C01.

All XLSX files are literal fictional fixtures generated by this harness. Scan,
review and Save use the real hosted company/core services and native SQLite.
"""
import copy
import hashlib
import json
import os
import sys
import tempfile
from pathlib import Path
from urllib.parse import urlsplit

from playwright.sync_api import expect, sync_playwright

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(os.environ['WAVELINK_TEST_SOURCE']).resolve()
sys.path.insert(0, str(SOURCE))
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / 'tests'))
from test_company_c01 import PASS, activate, client, instance
from browser_import_row_selection_ui105 import selection_workbook

OUT = Path(os.environ.get('WAVELINK_UI109_EVIDENCE_DIR', str(ROOT.parent / 'evidence/browser')))
TOPICS = ['documentimport', 'importcentre', 'inventorybuilder', 'toolboxbuilder', 'toolbox']
TRACKED = ('app/document_import.py', 'app/document_structure.py', 'app/document_extract.py',
           'app/log_schema.py', 'app/toolbox.py', 'app/browser_toolbox.py', 'app/builder_hub.py',
           'app/static/document_import.js', 'app/static/document_import.css', 'app/static/setup_builders.js',
           'app/static/index.html', 'app/static/sw.js', 'app/static/help_workspace.js',
           'app/static/help_workspace.css', 'app/static/help_catalogue.json', 'app/static/help.css',
           *['app/static/help_topics/' + topic + '.html' for topic in TOPICS],
           *['docs/user/topics/' + topic + '.html' for topic in TOPICS])


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    sha = lambda path: hashlib.sha256(path.read_bytes()).hexdigest()
    chrome = Path(os.environ['WAVELINK_CHROMIUM_EXECUTABLE']).resolve()
    report = dict(checks=[], errors=[], widths=[1440, 390, 320], screenshots=[],
                  method='Real Chromium, genuine IndexedDB, disposable fictional C01 HostedBoundary/CompanyAccess/core APIs and native SQLite; generated literal fictional XLSX fixtures only.',
                  source_hashes={name: sha(SOURCE / name) for name in TRACKED}, served_asset_hashes={},
                  harness_sha256=sha(Path(__file__)), runtime_manifest_sha256=sha(SOURCE / 'RELEASE_FILES.json'),
                  chromium_executable_sha256=sha(chrome),
                  repository_helper_hashes={name: sha(ROOT / 'tests' / name) for name in ['test_company_c01.py', 'browser_import_row_selection_ui105.py']},
                  limitations=['Service-worker registration and WebSockets are suppressed.',
                               'No production, Render, live mail, physical camera, Windows display or worker-upgrade acceptance.',
                               'Only clear printed operational headings and explicit Topic/Discussion definitions are proposed; changed layouts remain located review points.',
                               'Help full-text search is exercised through the served catalogue; offline guides are checked as their actual standalone files.'])

    def ok(name):
        report['checks'].append(name)
        (OUT / 'PROGRESS.json').write_text(json.dumps(report, indent=2) + '\n')

    with tempfile.TemporaryDirectory(prefix='fictional-ui109-definitions-') as td:
        td = Path(td)
        log = td / 'Fictional_UI109_Daily_Log.xlsx'
        selection_workbook(log, [('Fictional daily log', [
            (2, ['Vessel', 'Fictional Aurora']), (5, ['Instructions', 'Record fictional pressure after isolation.']),
            (9, ['Date', 'Time UTC', 'Pressure (bar)', 'Event']),
            (13, ['2026-10-10', '12:15', 18, 'HISTORICAL-EVENT-109']),
            (17, ['Date', 'Wind speed (kn)', 'Wave height (m)']),
            (21, ['2026-10-10', 15, '1.3'])])])
        numeric = td / 'Fictional_UI109_Weather_Log.xlsx'
        selection_workbook(numeric, [('Fictional weather log', [
            (3, ['Vessel', 'Fictional Aurora']),
            (7, ['Date', 'Time UTC', 'Wind speed (kn)', 'Wave height (m)', 'Voltage (V)', 'Current (A)', 'Depth [m]', 'Duration (min)']),
            (15, ['2026-10-10', '12:15', 15, '1.3', 24, '1.8', 300, 12])])])
        unsupported = td / 'Fictional_UI109_No_Header_Log.xlsx'
        selection_workbook(unsupported, [('Fictional daily log', [
            (2, ['Vessel', 'Fictional Aurora']), (5, ['Crew', 'HISTORICAL-PERSON-109']),
            (9, ['2026-10-10', '12:15', 18, 'HISTORICAL-EVENT-109'])])])
        toolbox = td / 'Fictional_UI109_Toolbox.xlsx'
        selection_workbook(toolbox, [('Sheet1', [
            (2, ['Instructions', 'Review the fictional safe lift plan.']),
            (5, ['Supervisor instructions', 'Confirm the fictional exclusion area.']),
            (9, ['Topic', 'Discussion points', 'Name', 'Answer']),
            (13, ['Safe lift', 'Discuss fictional hand signals', 'HISTORICAL-NAME-109', 'HISTORICAL-ANSWER-109']),
            (17, ['Controls', 'Confirm fictional exclusion area', 'HISTORICAL-NAME-110', 'HISTORICAL-ANSWER-110'])])])
        report['fictional_fixture_hashes'] = {path.name: sha(path) for path in [log, numeric, unsupported, toolbox]}
        installation = instance.__wrapped__(td)
        with client(installation) as c, sync_playwright() as pw:
            activate(c)
            origin = installation[2].external_origin
            store = c.app.state.core.state.store
            browser = pw.chromium.launch(headless=True, args=['--no-sandbox'], executable_path=str(chrome))
            report['chromium_version'] = browser.version
            p = browser.new_page(viewport={'width': 1440, 'height': 1000})
            p.set_default_timeout(30000)
            p.on('pageerror', lambda error: report['errors'].append(str(error)))
            p.on('dialog', lambda dialog: dialog.accept())
            p.add_init_script('class ReviewSocket{constructor(){this.readyState=3;}close(){}send(){}}window.WebSocket=ReviewSocket;WebSocket.OPEN=1;if(navigator.serviceWorker)navigator.serviceWorker.register=()=>Promise.resolve();')
            exchanges = []

            def route(r):
                req = r.request
                u = urlsplit(req.url)
                response = c.request(req.method, u.path + ('?' + u.query if u.query else ''), headers=req.headers, content=req.post_data_buffer)
                source_name = 'app' + u.path
                if u.path.startswith('/help/topics/') and u.path.rsplit('/', 1)[-1] in TOPICS:
                    source_name = 'app/static/help_topics/' + u.path.rsplit('/', 1)[-1] + '.html'
                if source_name in TRACKED and response.status_code == 200:
                    report['served_asset_hashes'][source_name] = hashlib.sha256(response.content).hexdigest()
                if u.path.startswith('/api/builders/document/'):
                    exchanges.append(dict(path=u.path, status=response.status_code, request=json.loads(req.post_data or '{}'), response=response.json()))
                r.fulfill(status=response.status_code, body=response.content, headers=dict(response.headers))

            p.route(origin + '/**', route)

            def latest(suffix):
                return next(x for x in reversed(exchanges) if x['path'].endswith('/' + suffix))

            def counts():
                with store.connection() as con:
                    return {table: con.execute('SELECT count(*) FROM ' + table).fetchone()[0] for table in ['ops_logbooks', 'ops_log_entries', 'ops_log_references', 'ops_log_media', 'records', 'toolbox_templates', 'toolbox_talks']}

            def builder(path):
                if p.locator('#sb-done').count():
                    p.locator('#sb-done').click()
                if p.locator('#sb-close').count():
                    p.locator('#sb-close').click()
                p.evaluate("()=>{location.hash='#builders';render();}")
                expect(p.locator('#sb-document')).to_be_visible()
                p.locator('#sb-document').click()
                p.locator('#sb-file').set_input_files(str(path))
                expect(p.locator('#di-kind')).to_be_visible(timeout=90000)
                assert latest('scan')['status'] == 200, latest('scan')['response']
                return copy.deepcopy(latest('scan')['response'])

            def review():
                p.locator('#sb-review').click()
                expect(p.locator('#di-confirm')).to_be_enabled()
                assert latest('review')['status'] == 200, latest('review')['response']
                p.locator('#di-confirm').check()
                expect(p.locator('#sb-import-save')).to_be_enabled()
                return copy.deepcopy(latest('review')['request']['draft'])

            def save():
                p.locator('#sb-import-save').click()
                expect(p.locator('#sb-success')).to_be_visible()
                assert latest('action')['response']['saved']
                return copy.deepcopy(latest('action')['response'])

            def screenshot(name, locator):
                p.wait_for_function('()=>!document.querySelector("#toast")?.classList.contains("visible")')
                for width in report['widths']:
                    p.set_viewport_size({'width': width, 'height': 1000})
                    locator.evaluate('n=>n.scrollIntoView({block:"start"})')
                    p.evaluate('()=>scrollBy(0,-80)')
                    assert p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'), (name, width)
                    bounds = p.locator('#di-edit input:visible,#di-edit textarea:visible,#di-edit select:visible,#di-recognition-review button:visible').evaluate_all('(ns)=>ns.map(n=>{const b=n.getBoundingClientRect();return {id:n.id,left:b.left,right:b.right};})')
                    assert not [b for b in bounds if b['left'] < -1 or b['right'] > width + 1], (name, width, bounds)
                    filename = name + '_' + str(width) + '.png'
                    p.screenshot(path=str(OUT / filename))
                    report['screenshots'].append(filename)
                    ok(name.replace('_', ' ') + ' fits ' + str(width) + 'px without page overflow or clipped controls')
                p.set_viewport_size({'width': 1440, 'height': 1000})

            def field_lines():
                return [line.strip() for line in p.locator('#di-fields').input_value().splitlines() if line.strip() and not line.startswith('#')]

            def blank_history(draft):
                assert 'HISTORICAL-' not in json.dumps(draft)

            try:
                p.goto(origin + '/')
                p.locator('[name=login_id]').fill('admin')
                p.locator('[name=password]').fill(PASS)
                p.locator('#login-form button[type=submit]').click()
                expect(p.locator('#workspace-nav')).to_be_visible()
                assert p.evaluate('workspaceReady&&!workspaceIssue&&!storageFailed')
                before = counts()
                scan = builder(log)
                assert scan['kind'] == 'logbook'
                assert field_lines() == ['Date | date |', 'Time UTC | time |', 'Pressure (bar) | number | bar', 'Event | text |']
                blank_history(scan['draft'])
                assert all(label not in scan['draft']['fields'] for label in ['Vessel', 'Fictional Aurora', 'Instructions', 'Wind speed', 'Wave height', '2026-10-10', '12:15'])
                assert counts() == before
                selected = next(s for s in scan['sheets'] if s['name'] == scan['draft']['sheet'])
                points = [point for point in selected['recognition_review']['points'] if point['target']['role'] == 'log_fields']
                assert len(points) == 2
                assert {point['source']['row'] for point in points} == {9, 17}
                assert any('later' in point['reason'].lower() for point in points)
                p.locator('#di-recognition-review').evaluate('n=>n.open=true')
                p.locator('[data-di-recognition-jump="' + points[-1]['id'] + '"]').click()
                assert p.locator('#di-fields').evaluate('n=>document.activeElement===n')
                ok('The actual spreadsheet scan chooses printed Date/Time/Pressure/Event definitions after preamble, exposes located later schema at Excel row17 and its review action focuses editable log fields without writes or historical entries')
                screenshot('printed_log_fields', p.locator('#di-fields'))
                edited = review()
                blank_history(edited)
                reviewed = latest('review')['response']['review_token']
                p.locator('#di-recognition-review').evaluate('n=>n.open=true')
                p.locator('[data-di-recognition-jump="' + points[0]['id'] + '"]').click()
                assert p.locator('#di-confirm').is_checked() and latest('review')['response']['review_token'] == reviewed
                ok('Read-only recognition navigation retains the checked server receipt and requires no native write')
                saved = save()
                with store.connection() as con:
                    native = con.execute('SELECT definitions FROM ops_logbooks WHERE id=?', (saved['id'],)).fetchone()
                    definitions = json.loads(native['definitions'])
                fields = [f for section in definitions for f in section['fields']]
                assert [(f['label'], f['type'], f['unit']) for f in fields] == [('Date', 'date', ''), ('Time UTC', 'time', ''), ('Pressure (bar)', 'number', 'bar'), ('Event', 'text', '')]
                after = counts()
                assert after['ops_logbooks'] == before['ops_logbooks'] + 1
                assert all(after[key] == before[key] for key in ['ops_log_entries', 'ops_log_references', 'ops_log_media', 'records', 'toolbox_talks'])
                blank_history(definitions)
                ok('Reviewed native Save persists one empty four-field logbook with printed types/units and zero source entries, references or media')

                scan = builder(numeric)
                assert scan['kind'] == 'logbook'
                parsed = [line.split('|') for line in field_lines()]
                assert [(bits[0].strip(), bits[1].strip(), bits[2].strip()) for bits in parsed] == [
                    ('Date', 'date', ''), ('Time UTC', 'time', ''), ('Wind speed (kn)', 'number', 'kn'), ('Wave height (m)', 'number', 'm'),
                    ('Voltage (V)', 'number', 'V'), ('Current (A)', 'number', 'A'), ('Depth [m]', 'number', 'm'), ('Duration (min)', 'number', 'min')]
                assert 'Fictional Aurora' not in scan['draft']['fields']
                review()
                screenshot('common_numeric_log_headings', p.locator('#di-fields'))
                ok('Common weather, electrical, depth and duration headings produce reviewed number fields with printed units; completed readings stay in source preview')

                scan = builder(unsupported)
                if p.locator('#di-kind').input_value() != 'logbook':
                    p.locator('#di-kind').select_option('logbook')
                if p.locator('#di-sheet').input_value() != 'Fictional daily log':
                    p.locator('#di-sheet').select_option('Fictional daily log')
                assert field_lines() == []
                expect(p.locator('#di-recognition-review')).to_be_visible()
                p.locator('#di-recognition-review').evaluate('n=>n.open=true')
                expect(p.locator('#di-recognition-review')).to_contain_text('No clear printed log field header')
                p.locator('#di-fields').fill('# Fictional manual section\nDate | date |\nEvent | text |')
                edited = review()
                blank_history(edited)
                assert 'Vessel' not in edited['fields'] and 'Crew' not in edited['fields']
                ok('A log with metadata and historical rows but no clear header starts with no inferred fields and supports an explicitly reviewed manual definition')

                scan = builder(toolbox)
                assert scan['kind'] == 'toolbox'
                assert scan['draft']['sheet'] == 'Sheet1'
                outline = p.locator('#di-outline').input_value()
                assert all(text in outline for text in ['# Safe lift', 'Discuss fictional hand signals', '# Controls', 'Confirm fictional exclusion area'])
                assert p.locator('#di-questions').input_value() == '' and p.locator('#di-declaration').input_value() == ''
                assert p.locator('#di-supervisor_instruction').input_value() == 'Confirm the fictional exclusion area.'
                blank_history(scan['draft'])
                assert 'Review the fictional safe lift plan.' not in outline
                old_actions = sum(x['path'].endswith('/action') for x in exchanges)
                p.locator('#sb-review').click()
                expect(p.locator('#sb-result')).to_contain_text('question')
                assert p.locator('#di-confirm').is_disabled() and p.locator('#sb-import-save').is_disabled()
                assert sum(x['path'].endswith('/action') for x in exchanges) == old_actions
                ok('The generic Sheet1 explicit Topic/Discussion table is proposed as grouped reusable discussion only, excludes participant/answer values and requires missing native understanding questions and declaration')
                p.locator('#di-questions').fill('Can everyone explain the fictional exclusion zone?')
                p.locator('#di-declaration').fill('I understand the fictional briefing and can ask questions.')
                p.locator('#di-toolbox-copy-notes').click()
                edited = review()
                assert 'Review the fictional safe lift plan.' in edited['outline']
                blank_history(edited)
                screenshot('explicit_toolbox_discussion', p.locator('#di-outline'))
                saved = save()
                with store.connection() as con:
                    native = json.loads(con.execute('SELECT body FROM toolbox_templates WHERE id=?', (saved['id'],)).fetchone()[0])
                assert native['published'] is False and native['revision'] == 0
                definition = native['definition']
                assert len(definition['questions']) == 1
                assert definition['declaration'] == 'I understand the fictional briefing and can ask questions.'
                assert all(text in json.dumps(definition['prompts']) for text in ['Discuss fictional hand signals', 'Confirm fictional exclusion area', 'Review the fictional safe lift plan.'])
                blank_history(native)
                assert counts()['toolbox_talks'] == before['toolbox_talks']
                ok('Explicit source-note inclusion plus manually supplied questions/declaration saves one unpublished native Toolbox form without a completed talk or historical acknowledgements')

                guide = browser.new_page()
                guide.on('pageerror', lambda error: report['errors'].append(str(error)))
                guide.route(origin + '/**', route)
                for mode in ['served', 'offline']:
                    for topic in TOPICS:
                        guide.goto(origin + '/help/topics/' + topic if mode == 'served' else (SOURCE / 'docs/user/topics' / (topic + '.html')).as_uri())
                        guide.evaluate('document.documentElement.style.scrollBehavior="auto"')
                        if mode == 'served':
                            article = guide.locator('article.help-article').first
                            headings = article.locator('h2,h3').evaluate_all('(ns)=>ns.map(n=>({id:n.id,text:n.textContent}))')
                            links = guide.locator('details.help-outline a[href^="#"]').evaluate_all('(ns)=>ns.map(n=>n.getAttribute("href").slice(1))')
                            assert len(headings) == len(links) and [h['id'] for h in headings] == links
                            assert len(set(links)) == len(links) and all(links)
                            assert guide.locator('.help-topic-footer').evaluate('n=>!!(document.querySelector("article.help-article").compareDocumentPosition(n)&Node.DOCUMENT_POSITION_FOLLOWING)')
                            if topic in ['documentimport', 'importcentre', 'toolboxbuilder']:
                                assert guide.locator('#ui106-source-interpretation').evaluate('n=>!!n.closest("article.help-article")')
                        else:
                            article = guide.locator('main.wrap.layout > .content') if guide.locator('main.wrap.layout > .content').count() else guide.locator('main').first
                            assert article.count() == 1
                        for width in [1440, 320]:
                            guide.set_viewport_size({'width': width, 'height': 1000})
                            targets = article.locator('[id^="ui109"]')
                            target = targets.first if targets.count() else article
                            target.evaluate('n=>n.scrollIntoView({block:"start",behavior:"instant"})')
                            assert guide.evaluate('document.documentElement.scrollWidth<=innerWidth+1'), (mode, topic, width)
                            box = target.bounding_box()
                            assert box['x'] >= -1 and box['x'] + box['width'] <= width + 1 and box['width'] > (500 if width == 1440 else 200), (mode, topic, width, box)
                            filename = 'help_' + mode + '_' + topic + '_' + str(width) + '.png'
                            guide.screenshot(path=str(OUT / filename))
                            report['screenshots'].append(filename)
                            ok(mode.capitalize() + ' ' + topic + ' Help keeps current chapters in its content column at ' + str(width) + 'px; served chapter outlines match all headings and follow-up links follow the article')
                guide.goto(origin + '/help/topics/documentimport')
                guide.set_viewport_size({'width': 1440, 'height': 1000})
                queries = [('Needs source review', ['documentimport', 'importcentre', 'inventorybuilder']),
                           ('Find header row', ['documentimport', 'importcentre', 'inventorybuilder']),
                           ('Boxes and contents', ['documentimport', 'importcentre', 'inventorybuilder']),
                           ('Review source interpretation', ['documentimport', 'importcentre', 'toolboxbuilder']),
                           ('Recover interrupted Toolbox read', ['toolbox', 'toolboxbuilder'])]
                for query, expected_topics in queries:
                    guide.locator('#help-query').fill(query)
                    expect(guide.locator('#help-search-status')).to_contain_text('matching guide wording')
                    visible = guide.locator('[data-topic-row]:not([hidden])').evaluate_all('ns=>ns.map(n=>n.dataset.topicRow)')
                    assert set(expected_topics) <= set(visible), (query, expected_topics, visible)
                assert len(json.loads((SOURCE / 'app/static/help_catalogue.json').read_text())['topics']) == 77
                assert report['served_asset_hashes']['app/static/help_catalogue.json'] == report['source_hashes']['app/static/help_catalogue.json']
                ok('The actually served 77-topic catalogue finds current source-review, deep-header, box, interpretation and Toolbox-recovery wording in their intended guides')
                guide.close()
                assert not report['errors'], report['errors']
                assert all(value == report['source_hashes'][name] for name, value in report['served_asset_hashes'].items())
                assert all(sha(SOURCE / name) == value for name, value in report['source_hashes'].items())
                assert sha(SOURCE / 'RELEASE_FILES.json') == report['runtime_manifest_sha256']
                assert sha(Path(__file__)) == report['harness_sha256']
                assert sha(chrome) == report['chromium_executable_sha256']
                ok('Served tracked assets equal source pins; source, harness, Chrome and manifest remain unchanged and genuine workflows raise no unhandled JavaScript errors')
                report['passed'] = True
            except Exception:
                report['passed'] = False
                p.screenshot(path=str(OUT / 'FAILURE.png'))
                print(json.dumps(dict(status=p.locator('#sb-result').inner_text() if p.locator('#sb-result').count() else '', recent_api=[dict(path=x['path'], status=x['status']) for x in exchanges[-4:]])))
                raise
            finally:
                report['summary'] = dict(checks_passed=len(report['checks']), unexpected_errors=len(report['errors']))
                (OUT / 'UI109_DOCUMENT_DEFINITIONS_BROWSER_RESULTS.json').write_text(json.dumps(report, indent=2) + '\n')
                browser.close()
    print(json.dumps(report['summary']))


if __name__ == '__main__':
    main()
